service:
  name: aws-lambda-kinesis-req-dynamo

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "kinesis:GetRecords"
        - "kinesis:GetShardIterator"
        - "kinesis:DescribeStream"
        - "kinesis:ListStreams"
        - "kinesis:PutRecord"
        - "kinesis:PutRecords"
      Resource: "arn:aws:kinesis:${self:provider.region}:*:stream/*"
    - Effect: "Allow"
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

resources:
  Resources:
    HelloKinesisStream:
      Type: "AWS::Kinesis::Stream"
      DeletionPolicy: Retain
      Properties:
        Name: "${self:service.name}-${self:provider.stage}-page"
        ShardCount: 1
    PageTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

functions:
  hello:
    environment: # Service wide environment variables
      kinesisStreamName: "${self:service.name}-${self:provider.stage}-page"
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello

  kinesisoutput:
    handler: handler.kinesisoutput
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - HelloKinesisStream
              - Arn
          batchSize: 1
          startingPosition: LATEST
          enabled: true
