service:
  name: serverless-crawler-sample

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    PAGE_DYNAMODB_TABLE: ${self:service}-${self:provider.stage}-page
    URL_DYNAMODB_TABLE: ${self:service}-${self:provider.stage}-url
    SLOT_KINESIS_STREAM_NAME: "${self:service.name}-${self:provider.stage}-slot"
    SLOT_KINESIS_STREAM_PARTITION_KEY: "${self:service.name}-${self:provider.stage}-slot-partition"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "kinesis:GetRecords"
        - "kinesis:GetShardIterator"
        - "kinesis:DescribeStream"
        - "kinesis:ListStreams"
        - "kinesis:PutRecord"
        - "kinesis:PutRecords"
      Resource: "arn:aws:kinesis:${self:provider.region}:*:stream/*"
    - Effect: "Allow"
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*"

resources:
  Resources:
    SlotKinesisStream:
      Type: "AWS::Kinesis::Stream"
      DeletionPolicy: Retain
      Properties:
        Name: ${self:provider.environment.SLOT_KINESIS_STREAM_NAME}
        ShardCount: 1
    PageTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.PAGE_DYNAMODB_TABLE}
    UrlTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: url
            AttributeType: S
        KeySchema:
          - AttributeName: url
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.URL_DYNAMODB_TABLE}

functions:
  addUrl:
    environment: # Service wide environment variables
      URL_DYNAMODB_TABLE: ${self:provider.environment.URL_DYNAMODB_TABLE}
    handler: handler.addUrl
    events:
      - http:
          method: post
          path: add_url

  slot:
    environment: # Service wide environment variables
      SLOT_KINESIS_STREAM_NAME: ${self:provider.environment.SLOT_KINESIS_STREAM_NAME}
      SLOT_KINESIS_STREAM_PARTITION_KEY: ${self:provider.environment.SLOT_KINESIS_STREAM_PARTITION_KEY}
    handler: handler.slot
    events:
      - http:
          method: get
          path: slot

  crawl:
    handler: handler.crawl
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - SlotKinesisStream
              - Arn
          batchSize: 1
          startingPosition: LATEST
          enabled: true
